
service: diabetes_prediction

provider:
  name: aws
  runtime: python3.8

  stage: dev
  region: us-east-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sagemaker: InvokeEndpoint
      Resource: "arn:aws:sagemaker:us-east-1:438182078247:endpoint/v1-xgboost-diabetes"

  environment:
    SAGEMAKER_ENDPOINT_NAME: "v1-xgboost-diabetes"

functions:
  hello:
    handler: handler.detect_diabetes
    events:
      - http:
          path: sagemaker
          method: post
          cors: true