service: ner-api

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-2

package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
    - node_modules/**
    - .vscode/**
    - __pycache__/**
    - .ipynb_checkpoints/**
    - (*).ipynb

functions:
  recognize-named-entities:
    handler: handler.handle_request
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: ner
          method: post

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true
    noDeploy: []
    useDownloadCache: true
    useStaticCache: true

plugins:
  - serverless-python-requirements
