
service: diabetes_prediction_final

provider:
  name: aws
  runtime: python3.8

# you can overwrite defaults here
  stage: dev
  region: us-east-2

package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
    - node_modules/**

functions:
  hello:
    handler: handler.predict
    events:
      - http:
          path: predict-diabetes
          method: get
          request:
            parameters:
              queryString:
                pregnancies: true
                glucose: true
                bp: true
                skinthickness: true
                insulin: true
                bmi: true
                diabetespedigreefunction: true
                age: true


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true