service: car-make-model

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

package:
  exclude:
    - model.tar.gz
    - README.md
    - upload_s3.py
    - notebooks/**
    - aws_lambda_fastai/**

functions:
  car_make_model_identification_ResNet:
    handler: handler.lambda_handler
    memorySize: 3008
    timeout: 30
    events:
      - http:
          path: invocations
          method: post
    layers:
      - "arn:aws:lambda:us-east-2:934676248949:layer:pytorchv1-py36:2"
    environment:
      MODEL_BUCKET: 'fgc-trained-models-sagemaker'
      MODEL_KEY: 'car_make_model_fastai_resnet/model.tar.gz'