service: car-make-model

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

package:
  exclude:
    - model.tar.gz
    - README.md
    - upload_s3.py
    - notebooks/**
    - aws_lambda_fastai/**
    - node_modules/**

functions:
  car_make_model_identification_ResNet:
    handler: handler.lambda_handler
    memorySize: 3008
    timeout: 300
    events:
      - http:
          path: invocations
          method: post
    environment:
      MODEL_BUCKET: 'fgc-trained-models-sagemaker'
      MODEL_KEY: 'car_make_model_fastai_resnet/model.tar.gz'

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true
    noDeploy: []
    useDownloadCache: false
    useStaticCache: true

plugins:
  - serverless-python-requirements
